openapi: 3.0.3

info:
  title: Laskin
  version: 0.2.0

components:
  schemas:
    TwoArguments:
      type: object
      properties:
        a:
          type: string
          description: Первое число
        b:
          type: string
          description: Второе число
      required:
        - a
        - b

paths:
  /:
    get:
      operationId: api.hello
      responses:
        200:
          description: Hello from Laskin!
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message

  /less:
    post:
      operationId: api.less
      description: Меньше
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TwoArguments"
      responses:
        200:
          description: Да
        204:
          description: Нет

  /greater:
    post:
      operationId: api.greater
      description: Больше
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TwoArguments"
      responses:
        200:
          description: Да
        204:
          description: Нет

  /less-or-equal:
    post:
      operationId: api.less_or_equal
      description: Меньше или равно
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TwoArguments"
      responses:
        200:
          description: Да
        204:
          description: Нет

  /greater-or-equal:
    post:
      operationId: api.greater_or_equal
      description: Больше или равно
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TwoArguments"
      responses:
        200:
          description: Да
        204:
          description: Нет

  /equal:
    post:
      operationId: api.equal
      description: Равно
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TwoArguments"
      responses:
        200:
          description: Да
        204:
          description: Нет
