openapi: 3.0.3

info:
  title: Laskin
  version: 0.2.0

paths:
  /:
    get:
      operationId: api.hello
      responses:
        200:
          description: Hello from Laskin!
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message

  /greater-or-equal:
    post:
      operationId: api.greater_or_equal
      description: Больше или равно
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                a:
                  type: string
                  description: A
                b:
                  type: string
                  description: B
              required:
                - a
                - b
      responses:
        200:
          description: Да
        204:
          description: Нет
