openapi: 3.0.3

info:
  title: Калькулятор
  description: Математические операции.
  version: 0.3.0

servers:
  - url: https://tomoru-calculator.herokuapp.com/

components:
  schemas:
    BinaryArguments:
      type: object
      properties:
        a:
          type: string
          description: Первое число
        b:
          type: string
          description: Второе число
      required:
        - a
        - b

    RangeArguments:
      type: object
      properties:
        a:
          type: string
          description: Число
        b:
          type: string
          description: Левая граница
        c:
          type: string
          description: Правая граница
      required:
        - a
        - b
        - c

    Value:
      type: object
      properties:
        value:
          type: string
          description: Значение
      required:
        - value

  responses:
    Result:
      description: Результат
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Value"

paths:
  /less:
    post:
      operationId: laskin.api.less
      tags:
        - tomoru/call
      summary: Меньше
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BinaryArguments"
      responses:
        200:
          description: Да
        204:
          description: Нет
        500:
          description: Что-то пошло не так

  /greater:
    post:
      operationId: laskin.api.greater
      tags:
        - tomoru/call
      summary: Больше
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BinaryArguments"
      responses:
        200:
          description: Да
        204:
          description: Нет
        500:
          description: Что-то пошло не так

  /less-or-equal:
    post:
      operationId: laskin.api.less_or_equal
      tags:
        - tomoru/call
      summary: Меньше или равно
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BinaryArguments"
      responses:
        200:
          description: Да
        204:
          description: Нет
        500:
          description: Что-то пошло не так

  /greater-or-equal:
    post:
      operationId: laskin.api.greater_or_equal
      tags:
        - tomoru/call
      summary: Больше или равно
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BinaryArguments"
      responses:
        200:
          description: Да
        204:
          description: Нет
        500:
          description: Что-то пошло не так

  /equal:
    post:
      operationId: laskin.api.equal
      tags:
        - tomoru/call
      summary: Равно
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BinaryArguments"
      responses:
        200:
          description: Да
        204:
          description: Нет
        500:
          description: Что-то пошло не так

  /add:
    post:
      operationId: laskin.api.add
      tags:
        - tomoru/call
      summary: Сложить
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BinaryArguments"
      responses:
        200:
          $ref: "#/components/responses/Result"
        500:
          description: Что-то пошло не так

  /substract:
    post:
      operationId: laskin.api.substract
      tags:
        - tomoru/call
      summary: Вычесть
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BinaryArguments"
      responses:
        200:
          $ref: "#/components/responses/Result"
        500:
          description: Что-то пошло не так

  /multiply:
    post:
      operationId: laskin.api.multiply
      tags:
        - tomoru/call
      summary: Умножить
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BinaryArguments"
      responses:
        200:
          $ref: "#/components/responses/Result"
        500:
          description: Что-то пошло не так

  /divide:
    post:
      operationId: laskin.api.divide
      tags:
        - tomoru/call
      summary: Разделить
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BinaryArguments"
      responses:
        200:
          $ref: "#/components/responses/Result"
        500:
          description: Что-то пошло не так

  /exponentiate:
    post:
      operationId: laskin.api.exponentiate
      tags:
        - tomoru/call
      summary: Возвести в степень
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BinaryArguments"
      responses:
        200:
          $ref: "#/components/responses/Result"
        500:
          description: Что-то пошло не так

  /within-exclusive-range:
    post:
      operationId: laskin.api.within_exclusive_range
      tags:
        - tomoru/call
      summary: В строгом интервале
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RangeArguments"
      responses:
        200:
          description: Да
        204:
          description: Нет
        500:
          description: Что-то пошло не так

  /within-inclusive-range:
    post:
      operationId: laskin.api.within_inclusive_range
      tags:
        - tomoru/call
      summary: В нестрогом интервале
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RangeArguments"
      responses:
        200:
          description: Да
        204:
          description: Нет
        500:
          description: Что-то пошло не так
