openapi: 3.0.3

info:
  title: Laskin
  version: 0.2.0

servers:
  - url: https://tomoru-calculator.herokuapp.com/

components:
  schemas:
    TwoArguments:
      type: object
      properties:
        a:
          type: string
          description: Первое число
        b:
          type: string
          description: Второе число
      required:
        - a
        - b

paths:
  /less:
    post:
      operationId: laskin.api.less
      tags:
        - tomoru/call
      summary: Меньше
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TwoArguments"
      responses:
        200:
          description: Да
        204:
          description: Нет
        500:
          description: Что-то пошло не так

  /greater:
    post:
      operationId: laskin.api.greater
      tags:
        - tomoru/call
      summary: Больше
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TwoArguments"
      responses:
        200:
          description: Да
        204:
          description: Нет
        500:
          description: Что-то пошло не так

  /less-or-equal:
    post:
      operationId: laskin.api.less_or_equal
      tags:
        - tomoru/call
      summary: Меньше или равно
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TwoArguments"
      responses:
        200:
          description: Да
        204:
          description: Нет
        500:
          description: Что-то пошло не так

  /greater-or-equal:
    post:
      operationId: laskin.api.greater_or_equal
      tags:
        - tomoru/call
      summary: Больше или равно
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TwoArguments"
      responses:
        200:
          description: Да
        204:
          description: Нет
        500:
          description: Что-то пошло не так

  /equal:
    post:
      operationId: laskin.api.equal
      tags:
        - tomoru/call
      summary: Равно
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TwoArguments"
      responses:
        200:
          description: Да
        204:
          description: Нет
        500:
          description: Что-то пошло не так
